### PR TITLE
Correctly set path and arguments in POST request

### PR DESCRIPTION
**Pull request by Aluriak**
See  #8 for details

### CODE REVIEW

**Comment by kynan** [comment]
Can you elaborate how this helps? The path is already non-empty, so we're not getting the `/RPC2` default.

**Comment by Aluriak** [comment]
It's just to get the proper writing according to the reference. This shouldn't fix anything, just be a valid way of writing the url.

**Comment by kynan** [comment]
OK, I see what you mean. It's a misunderstanding though: a valid URI should contain a trailing `/` after the hostname when requesting the root path. But that's not what we're doing here: the path is `/lib/exe/xmlrpc.php` and adding a trailing `/` would break it.

**Comment by Aluriak** [comment]
Yes, you are right, i didn't saw that.

**Pull request closed without merging**
